fix unknown `activeMask` with HIP 6.3.0
The feature was introduced with HIP 6.3.1 see https://rocm.docs.amd.com/en/docs-6.3.1/about/release-notes.html#hip-6-3-1

```
warp/WarpUniformCudaHipBuiltIn.hpp:120:24: error: use of undeclared identifier '__activemask'; did you mean 'Activemask'?
  120 |                 return __activemask();
      |                        ^
```